version: '3.3'

networks:

  default:
    external:
      name: localstack-tutorial

volumes:

  localstack:

services:

  localstack:
    image: localstack/localstack:0.10.8
    container_name: localstack
    ports:
      - 8080:8080 # webui
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=ap-southeast-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - PORT_WEB_UI=8080
      - SERVICES=lambda,dynamodb
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
      - LAMBDA_REMOVE_CONTAINERS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack:/tmp/localstack/data
    depends_on:
      - docker-events-listener

  docker-events-listener:
    build:
      context: docker-events-listener-build # 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 4
      - ./terraform:/opt/terraform/
    environment:
      APPLY_TERRAFORM_ON_START: "true"
      INVOKE_LAMBDAS_ON_START: counter
