version: '3.7'

services:

  php_app:
    build:
      context: .
      dockerfile: Dockerfile-php-app
    volumes:
      - ./:/var/www/html

  nginx_app:
    image: nginx:1.18.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php_app

  php_xhgui:
    build:
      context: .
      dockerfile: Dockerfile-php-xhgui

  nginx_xhgui:
    build:
      context: .
      dockerfile: Dockerfile-nginx-xhgui
    ports:
      - 8081:80
    depends_on:
      - php_xhgui

  mongo:
    image: mongo:4.4.1
